# Site settings
title: Cameron Little
email: cameron@camlittle.com
description: "A collection of Cameron Little's thoughts and projects."
baseurl: ""
url: "https://camlittle.com"
timezone: America/Vancouver

markdown: kramdown
highlighter: rouge
permalink: /posts/:title

kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
