baseURL = "https://camlittle.com/"
languageCode = "en-us"
title = "Cameron Little's Website"

enableGitInfo = true

[params]
  description = "A collection of Cameron Little's thoughts and projects."
  author = "Cameron Little"
  email = "cameron@camlittle.com"

  gitUrl = "https://github.com/apexskier/camlittle.com/commit/"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
