baseURL = "http://camlittle.com/"
languageCode = "en-us"
title = "Cameron Little's Website"
description = "A collection of Cameron Little's thoughts and projects."
author = "Cameron Little"

[permalinks]
  posts = "/posts/:title"
  pages = ":title"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = "github"
