baseURL = "https://camlittle.com/"
languageCode = "en-us"
title = "Cameron Little's Website"
titleCaseStyle = "Chicago"
timeout = 25000

enableGitInfo = true
enableRobotsTXT = true

[author]
  name = "Cameron Little"
  email = "cameron@camlittle.com"

[params]
  description = "A collection of Cameron Little's thoughts and projects"
  gitUrl = "https://github.com/apexskier/camlittle.com/commit/"

  [params.sitemap]
    [[params.sitemap.entries]]
      absURL = "/go-template-validation"
    [[params.sitemap.entries]]
      absURL = "/lightsaber"
      lastMod = 2018-06-15T05:59:20
    [[params.sitemap.entries]]
      absURL = "/highschool-portfolio"
      lastMod = 2018-06-15T06:09:32
    [[params.sitemap.entries]]
      absURL = "/web-usability-coordinator"
      lastMod = 2018-06-15T06:09:32

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
