name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node Dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build media script
        run: npm run build-media-script

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true # required for css processing

      - name: Cache hugo caches
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build site
        run: |
          rm -rf public/
          hugo gen chromastyles --style=manni > assets/css/highlight_light.css
          hugo gen chromastyles --style=native > assets/css/highlight_dark.css
          hugo --minify

      - name: Package artifact
        run: tar -cvzf artifact.tgz media-script/ public/ data/

      - name: Upload artifacts for deploy
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          retention-days: 2
          path: artifact.tgz

  deploy:
    runs-on: ubuntu-20.04
    needs:
      - build
    if: ${{ github.event_name == 'push' }}
    environment: matheny_prod
    steps:
      - name: Download artifacts for deploy
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Unpackage artifact
        run: tar -xvzf artifact.tgz

      - name: Upload media
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          node ./media-script

      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup ssh known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync prod
        run: |
          rsync -avz --checksum --delete ./public/ matheny.camlittle.com:/var/www/camlittle.com/
